import Head from "next/head";
import { Header } from "@/containers/header";
import PageHome from "@/containers/page-home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PageHome />
    </>
  );
}
