name: CI/CD for Next.js Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Укажите нужную версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel (или другой хостинг)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Добавьте ваш токен в Secrets репозитория
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # ID вашего проекта на Vercel
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # ID вашей организации на Vercel (если применимо)
        run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --confirm --scope $VERCEL_ORG_ID --project $VERCEL_PROJECT_ID